import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { ThemeProvider } from "@/context/ThemeProvider";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.className} antialiased min-h-screen flex flex-col justify-between`}
			>
				<ThemeProvider>
					<Header />
					<div className="flex-1 pt-20">{children}</div>
					{/* <Footer /> */}
				</ThemeProvider>
			</body>
		</html>
	);
}
