import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Montserrat } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { CartProvider } from "@/context/CartProvider";
import { ThemeProvider } from "@/context/ThemeProvider";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${montserrat.className} antialiased min-h-screen flex flex-col justify-between dark:bg-black dark:text-white`}
				>
					<ThemeProvider>
						<CartProvider>
							{children}
							<Toaster />
						</CartProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
